[phases.setup]
cmds = ["install-php-extensions gd zip exif intl"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction"]

[start]
cmd = "frankenphp php-server --listen 0.0.0.0:$PORT"
