[phases.setup]
nixPkgs = ["php85", "php85Extensions.zip", "php85Extensions.pdo_mysql", "php85Extensions.gd", "php85Extensions.intl", "php85Extensions.opcache", "php85Extensions.mbstring"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
